### ISSUE TITLE
Page blank when attempting to print or download data from osm

### ISSUE THREAD

**Issue by jokuNimi** [openstreetmap/merkaartor#103]
The print dialog (file->print) shows a blank page, and saves a blank image, even though a map is visible in the main view (a local osm file or one downloaded through 'WWW link (OSM/Google Maps)'). The map was visible in the download-dialog when I first installed the application, until I pressed the V next to it while trying to figure out what it does. A reinstall didn't get it to reappear.

Sometimes while trying to download a map, a loading dialog opens but doesn't seem to do anything (see attachment).

I'm on Arch linux and installed Merkaartor from the aur package. I don't know how to troubleshoot the issue further, but will gladly supply more information if just told how.

![2016-05-25-144411_507x537_scrot](https://cloud.githubusercontent.com/assets/8011580/15538824/38be8c5e-2287-11e6-8c3d-9bdcb77ce6df.png)

**Comment by Krakonos** [comment]
Allright, there is one known bug in play, and some unknown:

1) The download dialog from your screenshot is a bug #61 . It's already solved, but the latest release isn't out yet as there are still some problems I wanted to fix, but didn't have time to. If you can recompile with qt4, it should be OK (or use git version). It should be trivial to modify the PKGBUILD for latest snapshot, but it depends on your installation method (I'm no arch expert, but I think there is multitude ways of installing from aur).

2) The print is broken. It works reasonably well if you print to an actual printer, but I had limited success rendering into a pdf. I suspect though you misunderstand the print functionality. It is supposed to print the actual downloaded portion of the map. That is, you first need to download the map you're interested in, and then print it. If your document is empty, there is nothing to show in the print dialog. Note that background layers are not printed and I don't think they can be printed in the current version.

3) In the download map dialog, a preview should be present. You can try running wireshark or similar software to see if it's getting the tiles. This preview map is loaded online from tile.openstreetmap.org. Try zooming in and out (mouse wheel and panning works as expected, you don't have to use the +- buttons). If it doesn't help, try moving ~/.config/Merkaartor/Merkaartor.conf somewhere else and see if it helps. You can send it to me if it fixes the problem for you, so that I can examine it further, but beware that it contains confidential information if you entered some (username, password, file history), so take look before you send it.

4) The "V" button seems to be a shortcut for "Viewport", and sets the preview map to the current viewport (at least I think it does this, I've never actually used it).

I'll try to find some time to build the next release so at least 1) is fixed, as it's pretty annoying. However, let me know you investigate 3) further, so I can possibly include it if it's simple enough.

**Comment by jokuNimi** [comment]
Overall my problems seem to have been solved by installing the [merkator-git](https://aur.archlinux.org/packages/merkaartor-git/) package.

1) I haven't seen the download dialog pop up randomly again, with the git version. It doesn't seem to be measuring the progress for the download though. (As for arch: there are helpers for aur which might cause people to be unfamiliar with editing PKGBUILDs. Modifying it should be trivial though, either within the helperer or a manual install.)

2) Printing works as expected now, with the git version. I have a map loaded from a local file (which I manually downloaded from osm.org), and can print to both svg and png. I did the same before, so I don't think my issue was a misunderstanding. It works with the git version though, so all's good.

3) Something fishy is going on here, but everything is working as it should now. The preview map was restored after installing the git version, but went blank after pressing the viewport (V) button. A reboot and pressing the viewport button again restored it, and now it's been fine. So something weird seems to be going on between the preview map and the V-button, but I can't reproduce anything. If the issue reappears, I'll report back. (As an aside: I agree with feature request #91. Sometimes you want to download a map that is not in the shape of the viewport, and for me it's more comfortable to be in control of the selected area.)

4) I can't quite understand what the V button is doing, but it seems to be related to the the main window map somehow, but not in a very intuitive way.

**Comment by Krakonos** [comment]
Thanks for reporting back!

1) Great to hear.
2) Allright, I can see that I fixed some of the printing in 55b5a1669a3ceb8413aaea8dc9799402bd747327, which is after 0.18.2. I guess this fixed (some of) your problems.
3+4) I think I got it. First of all, the V button really applies the viewport from the main view. However in doing so, it somehow breaks the control so it's showing some empty part of our universe. You could probably scroll to the right place, but that would take forever. To reproduce it, zoom out the main view so much the planet won't show up, and the scale states "0m", the try the download dialog :-)

I will keep this bug open until I solve 3+4. I just need to find all the places to place constraints into.

As for #91, I fully agree, and will at least change the zoom level limit while I'm tackling this part.

**Comment by Krakonos** [comment]
Done. At least I'm not able to reproduce the bug. Please test the current master and reopen if I missed something.

**Comment by jokuNimi** [comment]
I'm not able to reproduce the bug either with the current master. Thanks!
