### ISSUE TITLE
Downloader authentication required and provided - can't upload changes

### ISSUE THREAD

**Issue by MaestroGlanz** [openstreetmap/merkaartor#129]
This seems to be a bug or a major flaw.

Step by step:

-I download a part of osm
-I create some stuff
-I say upload to osm
-first time: add login infos
-Errormessage: Downloader authentication required and provided -> I click okay (no other possibility)
-another error message: Title=Fehler beim Hochladen der Anforderung, Message = "Bitte Benutzernamen und Kennwort in den Einstellungen überprüfen"

What I tried so far:
- re-insert the password
- use email address instead of username
- Go offline in my browser, since I have osm-tabs open (double login)

Possible reasons:
- merkaartor uses windows internet functions (internet explorer and/or specific services); On my system everything related to internet explorer or system services not needed definitely is switched off. Switching some of it on is probably no option.

Impossible reasons:
- Internet connection works fine, download of maps and background pictures is no problem.

**Comment by MaestroGlanz** [comment]
I "solved" it:

My password contained letters, numbers and a special character. This has been the €-sign which is a non-ASCII-code-character. It seems to be that only ASCII-chars are allowed.

This causes also issues on the help.openstreetmap.org page, but not on the osm page itself.

A password change solved it.

**Comment by Krakonos** [comment]
Thanks for letting me know. I will look into it!

**Comment by Krakonos** [comment]
Allright, so I'm not definitely sure about this, but I think it might be due to some kind of encoding mismatch. For example, I'm not sure what Qt does with different locales, though I believe it should handle them as UTF-8.

As Merkaartor uses QAuthenticator to handle the HTTP authentication part, there is very little I could do. However, I think this would be resolved by implementing OAuth per #104 .

I'm closing this issue and it will most likely get fixed in 0.19.0, but no promises there.

**Comment by Systemk2** [comment]
I just ran into the same problem with v0.18.3 : I chose a password with an umlaut ("ü") and it gave me an authentication failure. Changing the PW to something without umlauts solved the problem
