### ISSUE TITLE
Error Uploading OSM Data

### ISSUE THREAD

**Issue by wirepiper** [openstreetmap/merkaartor#140]
Merkaartor's Error Message:

Error transferring http://www.openstreetmap.org/api/0.6/ changeset/51956039/upload - server replied: Conflict

![merkaartor_error_uploading_data_screenshot_2017-09-11_17-55-53](https://user-images.githubusercontent.com/15712539/30299040-e7e7dd20-971b-11e7-8bc4-2d9a142a6a0e.png)
![merkaartor_error_uploading_data_screenshot_2017-09-11_17-56-35](https://user-images.githubusercontent.com/15712539/30299041-e7e87bf4-971b-11e7-97fa-80eb2460f932.png)
![merkaartor_error_uploading_data_screenshot_2017-09-11_17-57-19](https://user-images.githubusercontent.com/15712539/30299042-e7ed251e-971b-11e7-966d-dc22b7c35dbb.png)

[Merkaartor_mdc_files.zip](https://github.com/openstreetmap/merkaartor/files/1294196/Merkaartor_mdc_files.zip)

**Comment by stephan75** [comment]
Maybe see http://wiki.openstreetmap.org/wiki/Beginners_Guide_1.4.2#How_to_avoid_conflicts_.28optional.29 ... 

aditionally search the OSM wiki for the keyword conflict.

**Comment by Krakonos** [comment]
So the problem seems to be with the little house with housenumber 18. Someone changed it while you were editing. 

Unfortunately, there is no good way of dealing with that. The best advice I can give you to follow what @stephan75  mentioned. For rescuing your current work, try to remove the offending way from the mdc file and upload the reset. But this requires some xml editing skills.

**Comment by Krakonos** [comment]
The core problem was a conflict in the uploaded data with the current database. Not really a bug, though we could handle conflicts a bit more gracefully.
