### ISSUE TITLE
0.19.0 release doesn't launch

### ISSUE THREAD

**Issue by KAMiKAZOW** [openstreetmap/merkaartor#257]
![image](https://user-images.githubusercontent.com/3259076/131138560-0d3642d2-1f5d-45d5-81ad-7e2e37cad2d1.png)

**Comment by Biswa96** [comment]
The failed packages are updated. Please update msys2 packages using `pacman -Syyuu` and check if the program works.

**Comment by Krakonos** [comment]
Thanks. I run the build and it appears to work. @KAMiKAZOW would you mind testing?

https://cloudsmith.io/~merkaartor/repos/merkaartor-nightly/packages/?q=version%3A0.19.0

If it works, I'll sign this build and publish it instead of the win64 (as 0.19.0-1, noting the issue, but deleting the broken one).

**Comment by KAMiKAZOW** [comment]
Completely wiped the old installation (= remove C:\Program Files\Merkaartor manually after uninstall) and it works now. Thanks.

**Comment by Krakonos** [comment]
I published the updated installers and merged #258 to make sure the build fails in case similar issue with windeployqt is reintroduced.

**Comment by stephan75** [comment]
Very good efforts, guys!
Maybe we can also an update on http://merkaartor.be/ about the new release?

**Comment by Biswa96** [comment]
HTTP? 😨

**Comment by Krakonos** [comment]
Will do today. https is coming in the near future, but I need to migrate the hosting first to support it properly (I'm not going to manage the certs manually).
