### ISSUE TITLE
Moving in "Node" mode

### ISSUE THREAD

**Issue by fkv1** [openstreetmap/merkaartor#275]
When "Node" is selected in the toolbar, nodes can not only be created, but moved as well. However, the motion is jumpy. The nodes snap to some kind of a grid whose resolution is less fine than in dedicated "Move" mode. This makes the Node mode essentially unusable for node editing. But Move mode is also not optimal for node editing, because lines are sometimes moved instead of nodes.

In an earlier bugtracking system, I was told that the problem was that the Node mode snaps to geographical coordinates instead of screen coordinates (whereas the Move mode snaps to screen coordinates). This doesn't seem to have any purpose and it would be great if you could change it to screen coordinates to allow for smooth moving.

**Comment by Krakonos** [comment]
Actually, the node tool does not snap to a different grid. It turns out, it mismanaged the allowed snap points and tried to snap to the move node itself. This in turned cause the node to be only movable by distance more than the snap radius, since the node is moved while being dragged. This is fixed in pr #306 .

**Comment by Krakonos** [comment]
Merged to master, will be released as part of 0.20.1
