### ISSUE TITLE
Switch to api.openstreetmap.org API host

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/merkaartor#287]
Use `api.openstreetmap.org/api/` -and HTTPS- instead of `www.openstreetmap.org/api/*`.

(Is: https://github.com/openstreetmap/operations/issues/951); see also #286

**Comment by Krakonos** [comment]
This actually has more parts:
[ ] Changing the presets.
[ ] Enabling/enforcing https.
[ ] Providing a migration path (at least a warning when using non-https would do, possibly just error out and point out to the change).

**Comment by Krakonos** [comment]
This was merged in #299 , with one minor change - I used the www. host, not api. host. This is due to api. redirecting (I assume to www., don't remember exactly) and that breaks OAuth2 flow. I'm not sure who's right or wrong here, but I currently use the QNetworkAuth library which doesn't work on the api. host.
