### ISSUE TITLE
Segmentation fault in Feature.cpp:587

### ISSUE THREAD

**Issue by RM87** [openstreetmap/merkaartor#6]
Load saved file with some edits: http://web.zone.ee/rmihkel87-1/merkaartor/untitled.mdc
Zoom out  to 100m scale (or more) and click download more. After acknowledging the fact that conflicts exist Merkaartor segfaults in Feature.cpp:587
Line: 
 if ( (theFeature->layer()->isTrack()) && M_PREFS->getDisableStyleForTracks() ) return blankPainters();

**Comment by Krakonos** [comment]
Looks fixed in b9827c3ea4a556b7d291da64e39fe51e2bf7c28f, although I'm not sure how did you created the document. It looks like you uploaded some part of it before? That code is a a bit messy, I'll lok into it as part of bug #8, as it's probably related to it. In the mean time, at least it does not crash.
